### ISSUE TITLE
There is a significant issue in your code, please carefully review it.

### ISSUE THREAD

**Issue by Liminss** [ziwliu8/SIMGA#1]

**Comment by Liminss** [comment]
Thank you for your reply. The experimental results differ significantly from the data in your paper. By the way, the GPU I am using is the NVIDIA GTX 3090.
+-------------+-----------------+
| Environment |      Usage      |
+=============+=================+
| CPU         |     7.90 %      |
+-------------+-----------------+
| GPU         | 3.16 G/23.68 G  |
+-------------+-----------------+
| Memory      | 1.60 G/755.17 G |
+-------------+-----------------+
24 Dec 16:55    INFO  best valid : OrderedDict([('hit@10', 0.086), ('ndcg@10', 0.0504), ('mrr@10', 0.0396)])
24 Dec 16:55    INFO  test result: OrderedDict([('hit@10', 0.0652), ('ndcg@10', 0.0372), ('mrr@10', 0.0287)])

**Comment by ziwliu8** [comment]
The cause of poor performance may be related to your environment and package version, or settings in config, please follow the settings in the paper exactly, or provide more detailed logs. The current version performs fine on my machine, see the logs provided.
[Mamba4Rec-amazon-beauty-Jul-15-2024_09-25-10-11bb9e.log](https://github.com/user-attachments/files/18238143/Mamba4Rec-amazon-beauty-Jul-15-2024_09-25-10-11bb9e.log)

**Comment by Liminss** [comment]
Your response was very prompt, thank you. However, it seems that there are also some issues with the logs you provided, as strange layers have appeared in the network structure, such as feature_embed_layer. In addition, the inference speed and performance of the model, as well as the GPU usage, do not match the paper. Perhaps you used the best validation performance in your paper, but this approach seems unreasonable.

**Comment by ziwliu8** [comment]
The feature_embed_layer was introduced to replicate the results of the SMLP4Rec model and is not  actually included in this framework. In addition, for the naming problem of some layers, because the current gpu is occupied, this log is stored when the performance test in July, so there will be misalignment for some layers and modular naming. We will update the latest log as soon as possible. Or you can refer to the ipynb file for some instructions

**Comment by Liminss** [comment]
Thank you again for your reply. In fact, you avoided the most crucial issue. I don't think it's a friendly gesture to continue discussing, so I will end this topic.

**Comment by biubiu17** [comment]
I would like to ask whether the results reported in your paper are based on the best validation performance. When I reproduced the experiments, the test results differed significantly from those reported. Could you please clarify this?
